### ISSUE TITLE
Request for clip_vision folder path

### ISSUE THREAD

**Issue by Amazon90** [Shakker-Labs/ComfyUI-IPAdapter-Flux#15]
Previously installed the joycaption2 node in layerstyle, and the model `siglip-so400m-patch14-384` already exists in `ComfyUI\models\clip`.
Can you change the input of 'clip_vision' in the IPAdapterFluxLoader node to a local folder path

**Comment by miemu1** [comment]
"clip_vision": (["google/siglip-so400m-patch14-384","E:/AIhuihua/DT_comfyui/models/clip_vision/siglip-so400m-patch14-384"],),这是我的修改地址,我自己是可用的,你可以参考下

**Comment by king19871214** [comment]
> "clip_vision": (["google/siglip-so400m-patch14-384","E:/AIhuihua/DT_comfyui/models/clip_vision/siglip-so400m-patch14-384"],),这是我的修改地址,我自己是可用的,你可以参考下“剪辑视觉”： (["google/siglip-so400m-patch14-384","E:/AIhuihua/DT_comfyui/model s/clip_vision/siglip-so400m-patch14-384"],)，这是我修改的地址，我自己是可用的，你参考下

都试过了，还是不行，会报错，Incorrect path_or_model_id: 'F:\GoodLuck\ComfyUI\models\clip_vision\siglip-so400m-patch-384'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
路径或模型 ID 不正确：“F:\GoodLuck\ComfyUI\models\clip_vision\siglip-so400m-patch-384”。请提供本地文件夹的路径或集线器上模型的 repo_id。明明填的是正确的，/这个方向的也试过，还是不行。家人们有什么好办法啊。

**Comment by miemu1** [comment]
注意是/而不是\,你没改对

**Comment by miemu1** [comment]
你应该改为F：/GoodLuck/ComfyUI/models/clip_vision/siglip-so400m-patch-384

**Comment by king19871214** [comment]
> 你应该改为F：/GoodLuck/ComfyUI/models/clip_vision/siglip-so400m-patch-384

我试了，还是不行，会报错这样的错
Incorrect path_or_model_id: 'F：/GoodLuck/ComfyUI/models/clip_vision/siglip-so400m-patch-384'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
错误的path_or_model_id：'F：/GoodLuck/ComfyUI/models/clip_vision/siglip-so400m-patch-384'。请提供本地文件夹的路径或集线器上模型的 repo_id。

**Comment by king19871214** [comment]
> 符号错了,成大写了,在标题栏复制,然后把\改为/ ,你改后112行截图看看 ![1732624777402](https://private-user-images.githubusercontent.com/107423147/389954998-09cb5cb1-b8bd-43b5-ad6a-423b43c2112a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MjU2NDcsIm5iZiI6MTczMjYyNTM0NywicGF0aCI6Ii8xMDc0MjMxNDcvMzg5OTU0OTk4LTA5Y2I1Y2IxLWI4YmQtNDNiNS1hZDZhLTQyM2I0M2MyMTEyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxMjQ5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTBmZDE2YzdjOWEzYjY1NzliZTkxMjFmYWZkZTk1NGY3YjMwMWU5MzAzMGI1NGNkMGFjZjBkMWE1OGU1NGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YjpR7buSOUtFWSjCgYgGQqrjs_Yk5BMw2n_iJAOR78M) ![1732624869743](https://private-user-images.githubusercontent.com/107423147/389955145-d54b3385-453f-4cc4-af9f-abddb9e36a59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MjU2NDcsIm5iZiI6MTczMjYyNTM0NywicGF0aCI6Ii8xMDc0MjMxNDcvMzg5OTU1MTQ1LWQ1NGIzMzg1LTQ1M2YtNGNjNC1hZjlmLWFiZGRiOWUzNmE1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxMjQ5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWQwYjgyMTZmZGQyMzdmMzE5ZGEyMzZiYjVjYTgzYWI1ZGE4ZmY2NTUyYjEzNjM3NzMzMDI3Njc0NzU4NjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eoQjzhj-kj05rLRHhOFF_HUZqfLgGskuIpuECfJg_Qw)



> 符号错了,成大写了,在标题栏复制,然后把\改为/ ,你改后112行截图看看 ![1732624777402](https://private-user-images.githubusercontent.com/107423147/389954998-09cb5cb1-b8bd-43b5-ad6a-423b43c2112a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MjU2NDcsIm5iZiI6MTczMjYyNTM0NywicGF0aCI6Ii8xMDc0MjMxNDcvMzg5OTU0OTk4LTA5Y2I1Y2IxLWI4YmQtNDNiNS1hZDZhLTQyM2I0M2MyMTEyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxMjQ5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTBmZDE2YzdjOWEzYjY1NzliZTkxMjFmYWZkZTk1NGY3YjMwMWU5MzAzMGI1NGNkMGFjZjBkMWE1OGU1NGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YjpR7buSOUtFWSjCgYgGQqrjs_Yk5BMw2n_iJAOR78M) ![1732624869743](https://private-user-images.githubusercontent.com/107423147/389955145-d54b3385-453f-4cc4-af9f-abddb9e36a59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MjU2NDcsIm5iZiI6MTczMjYyNTM0NywicGF0aCI6Ii8xMDc0MjMxNDcvMzg5OTU1MTQ1LWQ1NGIzMzg1LTQ1M2YtNGNjNC1hZjlmLWFiZGRiOWUzNmE1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQxMjQ5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWQwYjgyMTZmZGQyMzdmMzE5ZGEyMzZiYjVjYTgzYWI1ZGE4ZmY2NTUyYjEzNjM3NzMzMDI3Njc0NzU4NjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eoQjzhj-kj05rLRHhOFF_HUZqfLgGskuIpuECfJg_Qw)

![Snipaste_2024-11-26_20-48-22](https://github.com/user-attachments/assets/8f4137e3-c2a5-45ae-a940-8e52ad7f5d7e)
还是不行

**Comment by miemu1** [comment]
这应该是系统环境不一样了,我之前也改过好多次都不行,昨天才突然可以的,我使用了感觉效果并不是太好,不知道是我的问题还是什么

**Comment by king19871214** [comment]
我看有些博主在测这个节点，看他们说是比之前的flux的IPA要好多就来试试，试了几次没想到用不了，你是不是加了CN来控制所以出的效果不是很好。你可以试试flux自已出的控制模型来试试看。

**Comment by Amazon90** [comment]
![1](https://github.com/user-attachments/assets/03ed6141-e4a5-4693-a1e0-6401fc40ed3a)
https://github.com/Shakker-Labs/ComfyUI-IPAdapter-Flux/issues/46#issuecomment-2509808575
