### ISSUE TITLE
出图效果和官方diffusers代码有些对不齐，生成的图像存在条纹

### ISSUE THREAD

**Issue by Magicalppj** [Shakker-Labs/ComfyUI-IPAdapter-Flux#40]
ComfyUI-IPAdapter-Flux版本：[345fb599c17a85b69505958e6f5b5732dd33ace1](https://github.com/Shakker-Labs/ComfyUI-IPAdapter-Flux/commit/345fb599c17a85b69505958e6f5b5732dd33ace1)
ComfyUI 版本：[commit](https://github.com/comfyanonymous/ComfyUI/commit/839ed3368efd0f61a2b986f57fe9e0698fd08e9f)
很棒的工作！但是我在使用的时候发现了一个效果上对不齐的问题。
使用本仓库中提供的workflow，正常load flux模型和ip adapter，没有报错，但是生成的图像中存在条纹栅格？如下图所示：
![Snipaste_2024-11-28_14-48-45](https://github.com/user-attachments/assets/02dd7fe1-b960-4e2b-a70f-e1861dcc6bd9)
![image](https://github.com/user-attachments/assets/13069afc-6585-41dd-bdc9-860832cb05fb)

但是同样使用huggingface上的[官方repo](https://huggingface.co/InstantX/FLUX.1-dev-IP-Adapter)，生成的图像是相对干净的？
![image](https://github.com/user-attachments/assets/1e5a3f8c-7379-4623-a1ba-22d62e522a48)

不确定是不是代码实现上的差别，测试reference图如下：
![0](https://github.com/user-attachments/assets/e66cbf45-071e-4317-a424-3b7126ce5421)
prompt: a girl playing guitar

测试官方repo的代码如下
```
import os
import pdb

from PIL import Image

import torch
import torch.nn as nn

from pipeline_flux_ipa import FluxPipeline
from transformer_flux import FluxTransformer2DModel
from attention_processor import IPAFluxAttnProcessor2_0
from transformers import AutoProcessor, SiglipVisionModel

from infer_flux_ipa_siglip import resize_img, MLPProjModel, IPAdapter

image_encoder_path = "google/siglip-so400m-patch14-384"
ipadapter_path = "./ip-adapter.bin"

dtype = torch.bfloat16
transformer = FluxTransformer2DModel.from_pretrained("black-forest-labs/FLUX.1-dev",subfolder='transformer', torch_dtype=dtype)


pipe = FluxPipeline.from_pretrained(
    "black-forest-labs/FLUX.1-dev", transformer=transformer, torch_dtype=torch.bfloat16)

ip_model = IPAdapter(pipe, image_encoder_path, ipadapter_path, device="cuda", num_tokens=128)

image_dir = "style_image.png"
image_name = image_dir.split("/")[-1]
image = Image.open(image_dir).convert("RGB")
image = resize_img(image)

prompt = "a girl playing guitar"

images = ip_model.generate(
    pil_image=image,
    prompt=prompt,
    scale=1,
    width=1024, height=1024,
    seed=42
)
os.makedirs('results', exist_ok=True)

images[0].save(f"results/{image_name}")
```

**Comment by yatoubusha** [comment]
大佬，走到采样器的时候，报错这个，可能会是什么原因呢？
![img_v3_02h2_0c96d1aa-f7cd-4e3a-a1b7-2c0117e2003g](https://github.com/user-attachments/assets/30a041fe-4f71-457f-86a3-c7974ac29381)

**Comment by philipy1219** [comment]
条纹栅格问题我们在diffusers的测试中也有发现，具体会存在于某些特定风格的图片中，将权重和结束步数调整一下会解决这个问题。diffusers和comfyui所用的推理设置、采样器和随机数生成机制都存在差别，生成的图像不会完全一致。

**Comment by Magicalppj** [comment]
> 大佬，走到采样器的时候，报错这个，可能会是什么原因呢？ ![img_v3_02h2_0c96d1aa-f7cd-4e3a-a1b7-2c0117e2003g](https://private-user-images.githubusercontent.com/34413340/390746731-30a041fe-4f71-457f-86a3-c7974ac29381.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDk0OTgsIm5iZiI6MTczMjg0OTE5OCwicGF0aCI6Ii8zNDQxMzM0MC8zOTA3NDY3MzEtMzBhMDQxZmUtNGY3MS00NTdmLTg2YTMtYzc5NzRhYzI5MzgxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAyNTk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZDU0Yzk1ZmIyMGFmZGNkOWEzNzA3OWVjYjZkNWRmNDdlMzdlZWY4MjdhZTYzMGJhYzYzMTJkN2RmYTg0NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LJR1QUdyyI41wY64EGzeP5VH2R57bZqJ_w653964q0U)

comfyUI版本问题吧？可以把本仓库的插件版本以及comfyui的版本回退一下，我现在用的两个版本是可用的

**Comment by Magicalppj** [comment]
> 条纹栅格问题我们在diffusers的测试中也有发现，具体会存在于某些特定风格的图片中，将权重和结束步数调整一下会解决这个问题。diffusers和comfyui所用的推理设置、采样器和随机数生成机制都存在差别，生成的图像不会完全一致。

感谢回答，看起来只能通过调参的方式解决了。
