### ISSUE TITLE
 Still don't work after the new updates...

### ISSUE THREAD

**Issue by poluramus** [Shakker-Labs/ComfyUI-IPAdapter-Flux#55]
The default workflow you provided still doesn’t work for me. I’m using the portable standalone build and installed the requirements.txt from the python_embeded\python.exe. I even tried recreating every node in the workflow you shared, but unfortunately, that didn’t resolve the issue. It’s quite frustrating, especially since I’ve been waiting for an update on that node for a while now.......

![Capture d’écran 2024-12-10 210328](https://github.com/user-attachments/assets/68ca8509-e121-447c-8595-383e7bced0f2)

**Comment by philipy1219** [comment]
The model input of Basic Guider should be model output of Apply IPAdapter Flux Model, not the output of Load Diffusion Model

**Comment by poluramus** [comment]
Thank you for the response and the fix commit 🙏 🙂
